### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by davipatricio** [lastfm4devs/lastfm-ts#4]
This is a list of methods and features lacking support in lastfm-ts.

- [ ] User tokens/authentication
- [x] Application tokens/authentication

- [ ] Album
  - [ ] `album.addTags` (requires User auth)
  - [ ] `album.getInfo`
  - [ ] `album.getTags`
  - [ ] `album.getTopTags`
  - [ ] `album.removeTag` (requires User auth)
  - [ ] `album.search`

- [ ] Artist
  - [ ] `artist.addTags` (requires User auth)
  - [ ] `artist.getCorrection`
  - [x] `artist.getInfo`
  - [x] `artist.getSimilar`
  - [ ] `artist.getTags`
  - [ ] `artist.getTopAlbums`
  - [ ] `artist.getTopTags`
  - [ ] `artist.getTopTracks`
  - [ ] `artist.removeTag` (requires User auth)
  - [x] `artist.search`
 
- [ ] Auth
  - [ ] `auth.getMobileSession` (requires User auth)
  - [ ] `auth.getSession` (requires User auth)
  - [ ] `auth.getToken` (requires User auth)
  
- [ ] Geo
  - [ ] `geo.getTopArtists`
  - [ ] `geo.getTopTracks`
  
- [ ] Library
  - [ ] `library.getArtists`

- [ ] Tracks
  - [ ] `track.addTags` (requires User auth)
  - [ ] `track.getCorrection`
  - [x] `track.getSimilar`
  - [ ] `track.getTags`
  - [x] `track.getInfo`
  - [ ] `track.getTopTags`
  - [ ] `track.love` (requires User auth)
  - [ ] `track.scrobble` (requires User auth)
  - [x] `track.search`
  - [ ] `track.unlove` (requires User auth)
  - [ ] `track.updateNowPlaying` (requires User auth)
